- name: add yum-utils
  sudo: yes
  yum:
    name: yum-utils
- name: Add Docker repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docer-ce.repo
  become: yes
- name: Install Docker
  yum:
    name: docker-ce-18.09.1
    state: present
  become: yes
- name: Install Docker CLI
  yum:
    name: docker-ce-18.09.1
    state: present
- name: Install Docker CLI
  yum:
    name: docker-ce-cli-18.09.1
    state: present
- name: Install containerd
  yum:
    name: containerd.io
    state: present
  become: yes
- name: Start Docker service
  service:
    name: docker
    state: started
    enabled: yes
  become: yes
- name: Add user centos to docker group
  user:
    name: centos
    groups:
      - docker
    append: yes
  become: yes
