- name: Update docker configuration
  copy:
    src: docker_daemon.json
    dest: /etc/docker/daemon.json
  become: yes
  notify: Restart Docker service
- name: Ensure SELinux is in permissive mode
  shell:
    cmd: |
      setenforce 0
      sed -i 's/^SELINUX=enforcing$/SELINUX=permissive/' /etc/selinux/config
    executable: /bin/bash
  become: yes
  notify: Restart Docker service
- name: Add Kubernetes repo
  copy:
    src: kubernetes.repo
    dest: /etc/yum.repos.d/kubernetes.repo
  become: yes
- name: Install kubeadm,kubelet,kubernetes-cni,kubectl
  yum:
    name: ['kubelet-1.19.1-0', 'kubectl-1.19.1-0', 'kubeadm-1.19.1-0', 'kubernetes-cni-0.8.7-0']
    state: present
    disable_excludes: kubernetes
  become: yes
- name: Ensure kubelet service is enabled
  systemd:
    name: kubectl
    enabled: yes
